### ISSUE TITLE
set_output with timecodes is broken

### ISSUE THREAD

**Issue by po5** [Irrational-Encoding-Wizardry/vs-preview#68] opened 2023-01-15 13:41 UTC
I generated a timecode file with vspipe on the very same clip I'm trying to output.  
`vspreview.set_output(clip, timecodes="timecodes_1.txt")`

I get the following error ([timecodes_1.txt](https://github.com/Irrational-Encoding-Wizardry/vs-preview/files/10420303/timecodes_1.txt)):  
`FramesLengthError: (set_timecodes) timecodes file length mismatch with clip's length! (timecodes=158, clip=159)`

Weirdly, manually adding one line to the timecodes file reports one less frame. ([timecodes_2.txt](https://github.com/Irrational-Encoding-Wizardry/vs-preview/files/10420304/timecodes_2.txt))  
`FramesLengthError: (set_timecodes) timecodes file length mismatch with clip's length! (timecodes=157, clip=159)`

Adding one more line jumps to 160 frames. ([timecodes_3.txt](https://github.com/Irrational-Encoding-Wizardry/vs-preview/files/10420305/timecodes_3.txt))  
`FramesLengthError: (set_timecodes) timecodes file length mismatch with clip's length! (timecodes=160, clip=159)`

**Comment by Setsugennoao** [comment] 2023-05-08 11:56
Switching to the vstools implementation fixed it on my end, can't reproduce it.
Please reopen the issue if it's not fixed in your setup.

**Closed by Setsugennoao** 2023-05-08 11:56 UTC
